server:
  port: 8501
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: account-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcl

    username: cassandra
    password: cassandra

