server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"