server:
  port: 8502

spring:
  application:
    name: ticket-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3307/microserviceapp
    username: root
    password: microserviceapp
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: ibrahim
    password: ibrahim
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/